dubbo:
  application:
    logger: slf4j
    name: dubbo3base
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: tri
    port: 50051

server:
  port: 8089

spring:
  application:
    name: dubbo3base
logging:
  file:
    path: ./samples/dubbo-samples/rpc/dubbo3/logs/
  level:
    root: info
    com.alipay.sofa.rpc.dubbo3: debug
  config: classpath:log4j2-spring.xml

# 1. 获取 bizName 的方式与 spring 不同，dubbo 使用的是 dubbo.application.name, 而不是 spring.application.name