name: Arkctl Unit Test
run-name: ${{ github.actor }} pushed arkctl code

on:
  push:
    branches:
      - master
    paths:
      - 'arkctl/**'

  pull_request:
    branches:
      - master
    paths:
      - 'arkctl/**'

  # enable manually running the workflow
  workflow_dispatch:

env:
  CGO_ENABLED: 0
  GOOS: linux
  WORK_DIR: arkctl

defaults:
  run:
    working-directory: arkctl

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: ${{ env.WORK_DIR }}/go.sum

      - name: Run go mod
        run: go mod download

      - name: Test
        run: make test

      #  https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
